list: $/butils/forms/models/form/columns.yaml
modelClass: Butils\Forms\Models\Form
title: Forms
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'butils/forms/forms/update/:id'
