name: Forms
form: $/sntools/forms/models/form/fields.yaml
modelClass: Sntools\Forms\Models\Form
defaultRedirect: sntools/forms/forms
create:
    redirect: 'sntools/forms/forms/update/:id'
    redirectClose: sntools/forms/forms
update:
    redirect: sntools/forms/forms
    redirectClose: sntools/forms/forms
