plugin:
    name: 'sntools.forms::lang.plugin.name'
    description: 'sntools.forms::lang.plugin.description'
    author: 'Sergio Neira'
    icon: oc-icon-envelope
    homepage: 'https://github.com/shneiravargas/wn-forms-plugin'
navigation:
    main-menu-item:
        label: Forms
        url: sntools/forms/messages
        icon: icon-life-ring
        sideMenu:
            messages:
                label: Messages
                url: sntools/forms/messages
                icon: icon-sitemap
            forms:
                label: Forms
                url: sntools/forms/forms
                icon: icon-sitemap
