name: Messages
form: $/butils/forms/models/message/fields.yaml
modelClass: Butils\Forms\Models\Message
defaultRedirect: butils/forms/messages
create:
    redirect: 'butils/forms/messages/update/:id'
    redirectClose: butils/forms/messages
update:
    redirect: butils/forms/messages
    redirectClose: butils/forms/messages
preview:
    redirect: butils/forms/messages
    redirectClose: butils/forms/messages
