name: Messages
form: $/sntools/forms/models/message/fields.yaml
modelClass: Sntools\Forms\Models\Message
defaultRedirect: sntools/forms/messages
create:
    redirect: 'sntools/forms/messages/update/:id'
    redirectClose: sntools/forms/messages
update:
    redirect: sntools/forms/messages
    redirectClose: sntools/forms/messages
preview:
    redirect: sntools/forms/messages
    redirectClose: sntools/forms/messages
