list: $/sntools/forms/models/message/columns.yaml
modelClass: Sntools\Forms\Models\Message
title: Messages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

recordUrl: 'sntools/forms/messages/preview/:id'
